### ISSUE TITLE
Comparação com br-validate-dfe-access-key

### ISSUE THREAD

**Issue by reinert** [zrpaplicacoes/br-dfe-validator#1]
Quais são as melhorias/diferenças implementadas neste fork em relação ao projeto original?

**Comment by RafaelTCostella** [comment]
Alguns minors:

- lib original não implementava suporte para diferentes tipos além de NFes. Essa daqui suporte NF-e, NFC-e de CF-e
- lib original não retornava o código do estado nas validations
