### ISSUE TITLE
Outros DFes

### ISSUE THREAD

**Issue by reinert** [zrpaplicacoes/br-dfe-validator#2]
Alguma previsão para suportar CTe e MDFe?

**Comment by RafaelTCostella** [comment]
A princípio não, mas posso estudar para deixar pronta até o final da semana que vem a princípio! :tada: 

Algo de mais urgente para antes disso?

Aceitamos PRs caso queira/possa ajudar!

**Comment by RafaelTCostella** [comment]
@reinert https://github.com/zrpaplicacoes/br-dfe-validator/pull/3 o modelo é bem semelhante! Você só poderia me fornecer cinco MDF-es válidas por favor para adicionar no PR?

**Comment by reinert** [comment]
Muito obrigado por sua responsividade! Sim, irei providenciar e anexo.
